'use strict';

module.exports = [ 'Alabama',
    'c:AL',
    'Alaska',
    'c:AK',
    'Arizona',
    'c:AZ',
    'Arkansas',
    'c:AR',
    'California',
    'c:CA',
    'Colorado',
    'c:CO',
    'Connecticut',
    'c:CT',
    'Delaware',
    'c:DE',
    'District of Columbia',
    'c:DC',
    'Florida',
    'c:FL',
    'Georgia',
    'c:GA',
    'Hawaii',
    'c:HI',
    'Idaho',
    'c:ID',
    'Illinois',
    'c:IL',
    'Indiana',
    'c:IN',
    'Iowa',
    'c:IA',
    'Kansas',
    'c:KS',
    'Kentucky',
    'c:KY',
    'Lousiana',
    'c:LA',
    'Maine',
    'c:ME',
    'Maryland',
    'c:MD',
    'Massachusetts',
    'c:MA',
    'Michigan',
    'c:MI',
    'Minnesota',
    'c:MN',
    'Mississippi',
    'c:MS',
    'Missouri',
    'c:MO',
    'Montana',
    'c:MT',
    'Nebraska',
    'c:NE',
    'Nevada',
    'c:NV',
    'New Hampshire',
    'c:NH',
    'New Jersey',
    'c:NJ',
    'New Mexico',
    'c:NM',
    'New York',
    'c:NY',
    'North Carolina',
    'c:NC',
    'North Dakota',
    'c:ND',
    'Ohio',
    'c:OH',
    'Oklahoma',
    'c:OK',
    'Oregon',
    'c:OR',
    'Pennsylvania',
    'c:PA',
    'Rhode Island',
    'c:RI',
    'South Carolina',
    'c:SC',
    'South Dakota',
    'c:SD',
    'Tennessee',
    'c:TN',
    'Texas',
    'c:TX',
    'Utah',
    'c:UT',
    'Vermont',
    'c:VT',
    'Virginia',
    'c:VA',
    'Washington',
    'c:WA',
    'West Virginia',
    'c:WV',
    'Wisconsin',
    'c:WI',
    'Wyoming',
    'c:WY'
];